// Each step introduces one idea before it is combined with earlier ideas.
const step = (title, text, code, output, explain, question, answer, table) => ({title,text,code,output,explain,question,answer,table});
const walkthroughs = [
{
intro:'先不看一大段程序。我们从一句“这张图得了 4.5 分”开始，把它翻译成计算机能读懂的写法。',
remember:['变量名是我们起的名字，= 是把右边的值交给左边。','数字不加引号；想原样保存的文字要加引号。','print(...) 是显示括号里的结果。'],
steps:[
step('先认清：代码和输出是两回事','代码是你交给计算机的指令；输出是执行指令后显示给你看的结果。本站展示代码和参考结果，填空区检查答案，不会执行完整 Python 程序。','print(4.5)','4.5',['print 可以先读作“显示”。','小括号 () 里放要显示的内容。','计算机不会把 print 这个单词也显示出来。'],'print(3) 会显示什么？','显示 3，不会显示 print(3) 这串代码。'),
step('变量：给一个值起名字','假设你给图片打了 4.5 分，希望后面还能用到这个分数，就给它起名叫 score。score 是英文“得分”，也可以换成别的合法名字。','score = 4.5\nprint(score)','4.5',['第一行：记住 score 这个名字现在指向 4.5。','第二行：查找 score 对应的值，再显示它。','= 不是询问两边是否相等，而是赋值。只赋值不会自动打印。'],'只写 score = 4.5，会自动显示 4.5 吗？','不会。它只是保存这个值，脚本里还需要 print 才会显示。'),
step('为什么有时要加引号？','数字 4.5 可以拿来计算；文字 "v2" 是一个版本名称。引号告诉 Python：里面是文字，请按文字理解。','model_version = "v2"\nscore = 4.5\nprint(model_version)\nprint(score)','v2\n4.5',['model_version 是变量名，含义是模型版本。下划线 _ 用来连接单词。','"v2" 是文字，也叫字符串。引号标记文字边界，通常不会被 print 打出来。','4.5 是小数，120 这样的值是整数。两种数字都可以计算。'],'"4.5" 和 4.5 完全一样吗？','不一样。前者是文字，后者是数字。看起来相似，但程序能对它们做的操作不同。'),
step('名字和名字里的值，不要混淆','看两个几乎一样的 print。一个没有引号，一个有引号，计算机会按两种方式处理。','score = 4.5\nprint(score)\nprint("score")','4.5\nscore',['没有引号的 score：去找这个变量的值，得到 4.5。','有引号的 "score"：直接显示这五个字母。','如果写成 Score，Python 会找另一个名字；它区分大小写。'],'要显示变量的值，应该写 print(score) 还是 print("score")？','写 print(score)。加了引号就变成显示名字本身了。'),
step('先计算，再打印','括号里也能放算式。Python 会先算出括号里的结果，再把结果交给 print。','score = 4.5\nsample_count = 120\nprint(score * sample_count)','540.0',['sample_count 是我们起的名字，意思是样本数量。','* 是乘号，4.5 × 120 = 540.0。','print 收到的是计算结果。这里只练习乘法，不代表真实评测总分。'],'print(2 + 3) 会显示 2 + 3 还是 5？','显示 5。算式先求值，结果再交给 print。'),
step('把几件小事放在一起','现在可以读完整例子了。程序按从上到下的顺序执行，前面保存的值，后面可以继续使用。','model_version = "v2"\nscore = 4.5\nsample_count = 120\nprint(model_version, score)\nprint(score * sample_count)','v2 4.5\n540.0',['前三行分别保存版本、分数和样本数。','print 里面的逗号表示同时显示两个值，默认用空格隔开。','最后一行先乘法再输出。这里没有需要背下来的算法。'],'把 score 改成 3，最后一行变成多少？','3 × 120 = 360。变量被使用的地方会取它当前的值。')]
},
{
intro:'现在只做一个决定：得分低于 3，就复查。先理解“条件是否成立”，再加入 if 和缩进。',
remember:['条件的结果是 True（成立）或 False（不成立）。','if 后面写条件，冒号后的缩进表示“条件成立时做什么”。','>= 包含等于；= 是赋值，== 才是比较相等。'],
steps:[
step('比较会得到“是”或“否”','我们已经知道 score 能保存分数。现在问计算机：这个分数是否小于 3？','score = 2.5\nprint(score < 3)','True',['< 表示小于，2.5 < 3 成立。','True 表示真，也就是“条件成立”；False 表示假。','这种只有真、假两种结果的类型叫布尔值。'],'3 < 3 会得到 True 吗？','不会，得到 False。3 等于 3，并不小于 3。'),
step('if：条件成立，才执行下面的动作','if 可以翻译成“如果”。冒号表示接下来要写这一条件对应的动作。','score = 2.5\nif score < 3:\n    print("需要复查")','需要复查',['先把 score 代入：如果 2.5 小于 3。','条件成立，所以执行缩进的 print。','print 前的 4 个空格叫缩进，表示这行属于 if 管理的范围。'],'如果把 score 改成 4，这段代码会打印什么？','不打印任何内容，因为 if 条件不成立，而且还没有安排其他分支。'),
step('else：不符合条件时怎么办？','如果希望高分也有反馈，就加上 else，读作“否则”。if 和 else 对齐，两个分支里的动作分别缩进。','score = 4\nif score < 3:\n    print("需要复查")\nelse:\n    print("通过")','通过',['4 < 3 不成立，所以跳过第一条 print。','转到 else，输出“通过”。','一次判断只走其中一个分支，不会两个都执行。'],'score 为 3 时走哪边？','走 else，输出“通过”。因为低分标准是严格小于 3。'),
step('把符号翻译成中文','筛选标准常出错在边界。不要只记符号，拿 2、3、4 三个分数代进去检查一下。','score = 3\nprint(score > 3)\nprint(score >= 3)\nprint(score == 3)','False\nTrue\nTrue',['> 是“大于”，>= 是“大于或等于”。','== 是“是否相等”；!= 是“是否不相等”。','score = 3 是保存分数，不是比较。'], '“3 分及以上”应该用 > 还是 >=？','用 >=，这样才不会漏掉恰好 3 分。',{headers:['写法','中文','score 为 3 时'],rows:[['score < 3','小于 3','False'],['score >= 3','大于或等于 3','True'],['score == 3','等于 3 吗','True']]}),
step('缩进不是装饰，它决定执行范围','最后一行没有缩进，所以它不属于 if 或 else 内部；无论走哪个分支，最终都要执行它。','score = 2\nif score < 3:\n    print("需要复查")\nelse:\n    print("通过")\nprint("检查结束")','需要复查\n检查结束',['先判断，打印“需要复查”。','else 的 print 被跳过。','继续往下，执行顶格的“检查结束”。'],'如果 score 改成 5，“检查结束”还会显示吗？','会。最后一行在条件分支外，不受分支选择影响。')]
},
{
intro:'这一节分成四层：一个列表、一个字典、列表里放字典、连续取值。前一层看懂了，再继续下一层。',
remember:['列表按位置取东西，从 0 开始编号。','字典按键找值，比如用 "score" 找到 2。','samples[0]["score"] 是先取第一条记录，再取记录里的分数。'],
steps:[
step('列表：把几个东西排成一排','先只放三个分数，不要同时考虑模型、编号等信息。外面的方括号 [] 把这些分数组成一个整体，叫列表。','scores = [2, 5, 3]\nprint(scores)','[2, 5, 3]',['scores 是列表的名字，英文表示“多个分数”。','2、5、3 是三个元素，也就是列表里的三个东西。','元素之间用逗号隔开；方括号告诉 Python 这里在创建列表。'],'这个列表里有几个元素？','3 个。2 是第一个元素，5 是第二个，3 是第三个。',{headers:['我们说的位置','Python 使用的编号','里面的值'],rows:[['第一个','0','2'],['第二个','1','5'],['第三个','2','3']]}),
step('列表取值：为什么第一个是 0？','Python 规定列表位置从 0 开始编号。先把它当作一种编号规则，不需要推导原因。这个编号叫“索引”或“下标”。','scores = [2, 5, 3]\nprint(scores[0])\nprint(scores[1])','2\n5',['scores[0]：去 scores 里取编号为 0 的那个值，得到 2。','scores[1]：取编号为 1 的那个值，得到 5。','创建列表时 [] 包住元素；接在名字后面时 [编号] 表示取值。'],'scores[2] 得到什么？','得到 3；scores[3] 则越界，因为这里只有 0、1、2 三个位置。'),
step('字典：不按位置，按标签找东西','一张图片除了分数，还有编号。用一个字典把这些信息装在一起：每个值前面贴一个标签。标签在代码里叫“键”。','sample = {"id": 1, "score": 2}\nprint(sample["score"])','2',['大括号 {} 创建字典，和列表的 [] 不一样。','"score": 2 中，"score" 是键，2 是值，冒号把它们配成一对。','两个键值对用逗号隔开。sample["score"] 是“找 score 标签对应的值”。'],'sample["id"] 得到什么？','得到 1，是编号标签 id 对应的值。',{headers:['键（标签）','值（内容）'],rows:[['"id"','1'],['"score"','2']]}),
step('列表和字典的区别，拿两个动作对比','它们都可以在后面接方括号来取值，但方括号里的东西不同：列表用位置编号，当前这个字典用文字键。','scores = [2, 5]\nsample = {"id": 1, "score": 2}\nprint(scores[0])\nprint(sample["score"])','2\n2',['scores[0] 的 0 是位置；它不是得分，也不是样本 id。','sample["score"] 的 "score" 是字段名，需要引号。','这两次刚好都得到 2，寻找方式却不同。'],'sample[0] 能取到 "id" 的值吗？','不能。这个字典没有数字键 0；它的两个键是 "id" 和 "score"。'),
step('组合：把两张“记录卡片”放进列表','一个字典代表一条样本。两条样本就可以用一个列表装起来。先只看最外层：samples 是一个装着两个字典的列表。','samples = [\n    {"id": 1, "model": "v1", "score": 2},\n    {"id": 2, "model": "v2", "score": 5}\n]\nprint(samples[0])',"{'id': 1, 'model': 'v1', 'score': 2}",['最外层 [] 表示一个列表。','里面每一对 {} 表示一条完整记录，两条记录用逗号分隔。','samples[0] 取出整个第一个字典，此时还没有单独取出得分。'],'samples 里有 2 个元素，还是 6 个元素？','2 个。每一个字典整体算一个元素，里面有几个字段不影响外层元素数量。'),
step('拆开 samples[0]["score"]','先把连续取值拆成两行。第一次取到一张记录卡，第二次才从卡片上找分数。','samples = [\n    {"id": 1, "model": "v1", "score": 2},\n    {"id": 2, "model": "v2", "score": 5}\n]\nfirst_sample = samples[0]\nscore = first_sample["score"]\nprint(score)','2',['samples[0] 得到第一个字典。把它暂时起名为 first_sample。','first_sample["score"] 再从这个字典里按键取值，得到数字 2。','这两次取值连起来写，就是 samples[0]["score"]。这里只是在同一条取值链上从左往右看。'],'samples[1]["score"] 呢？','先取第二个字典，再找 "score"，结果是 5。',{headers:['读到这里','现在拿到的东西','类型'],rows:[['samples','装着两条记录的整体','列表'],['samples[0]','id=1、model=v1、score=2 的记录','字典'],['samples[0]["score"]','2','数字']]}),
step('len：数外面这一层有多少个东西','len 可以读作“长度”。它只数交给它的对象，不会自动钻进每一层统计所有值。','samples = [\n    {"id": 1, "model": "v1", "score": 2},\n    {"id": 2, "model": "v2", "score": 5}\n]\nprint(len(samples))\nprint(len(samples[0]))','2\n3',['len(samples) 数外层列表：两条记录，所以是 2。','len(samples[0]) 先取第一个字典，再数它的键值对：三个，所以是 3。','不要把样本数量、字段数量、分数这三个概念混起来。'],'len([10, 20, 30, 40]) 是多少？','4。这里数的是元素个数，不是把数值相加。'),
step('报错也能拆开看：找不到的是位置还是键？','列表越界和字典缺少键是两类问题。报错不代表整段代码都错了，先看是哪一步没找到东西。','sample = {"id": 1, "score": 2}\nprint(sample.get("quality"))','None',['如果写 sample["quality"]，会出现 KeyError，因为字典里没有这个键。','get 是字典提供的查找方法：点号 . 表示使用 sample 的一个功能，括号里是要查的键。','sample.get("quality") 找不到时默认返回 None，意思是这里没有值；它不等于 0 分。'],'samples[9] 报错时，应该先检查什么？','先检查列表长度和位置编号，而不是去修改 "score" 这个键。')]
},
{
intro:'先让程序逐个看分数，再筛选，再收集结果；最后才把判断标准放进函数。不要一开始就同时理解 for、def、return。',
remember:['for 每次取一个元素，并重复执行缩进的动作。','append 把一个值加入列表末尾。','def 定义可重复使用的函数；return 把结果交还给调用它的地方。'],
steps:[
step('for：把同一个动作做几次','如果有一百个分数，不应该手写一百次 print。for 会依次拿出每个分数，替你重复执行动作。','scores = [2, 5, 3]\nfor score in scores:\n    print(score)','2\n5\n3',['for score in scores 读成“从 scores 里，每次拿一个值，暂时叫它 score”。','score 是你起的临时名字，不是 Python 规定只能这样叫。','缩进的 print 每轮执行一次。循环结束后再往下走。'],'这段循环里 print 被执行了几次？','3 次，因为 scores 有 3 个元素。',{headers:['轮次','score 当前的值','动作'],rows:[['第 1 轮','2','打印 2'],['第 2 轮','5','打印 5'],['第 3 轮','3','打印 3']]}),
step('循环里加一个判断','每轮拿到一个分数后，都问一次“是否低于 3”。这时有两层缩进：一层属于循环，一层属于条件。','scores = [2, 5, 3, 1]\nfor score in scores:\n    if score < 3:\n        print(score)','2\n1',['2 低于 3，打印；5 不低于 3，跳过打印。','3 不低于 3，也跳过；1 低于 3，打印。','if 每轮都判断，但最里面的 print 只有条件成立才执行。'],'循环执行 4 轮，print 也一定执行 4 次吗？','不一定。这里条件只成立两次，所以只打印 2 和 1。'),
step('用空列表收集结果','显示在屏幕上还不够，我们希望后面能继续使用这些低分。先准备一个空列表，再把符合标准的分数加入其中。','low_scores = []\nlow_scores.append(2)\nlow_scores.append(1)\nprint(low_scores)','[2, 1]',['[] 里什么都没有，表示空列表。','点号 . 表示使用这个列表的功能；append 是“追加一个元素”。','append(2) 把数字 2 放到列表末尾。它会修改列表，不需要重新赋值。'],'执行两次 append 后，列表里有几个元素？','2 个。先加入 2，再加入 1，因此顺序也是 2、1。'),
step('把循环、判断、收集连起来','现在把上一小步的手动追加，换成每轮符合条件时自动追加。','scores = [2, 5, 3, 1]\nlow_scores = []\nfor score in scores:\n    if score < 3:\n        low_scores.append(score)\nprint(low_scores)','[2, 1]',['low_scores 只在循环开始前创建一次。','第 1 轮变成 [2]；第 2、3 轮不变；第 4 轮变成 [2, 1]。','最后的 print 顶格写，表示等整个循环结束后再显示一次。'],'为什么不把 low_scores = [] 写在循环里面？','那样每轮都会重新建一个空列表，把前面收集的结果丢掉。'),
step('函数：给一段操作起名字','“低于 3 分”可能在很多地方用到。def 可以把这个判断定义为一个函数，以后按名字调用。','def is_low_quality(score):\n    return score < 3\n\nprint(is_low_quality(2))\nprint(is_low_quality(5))','True\nFalse',['def 是定义函数；is_low_quality 是我们起的函数名。','定义时的 score 是参数名，可以理解为等待传入分数的空位。','调用 is_low_quality(2) 时，2 填进这个空位，计算 2 < 3，再由 return 返回 True。'],'只有 def 这两行、没有调用时，会打印 True 吗？','不会。定义是在说明“以后怎么做”，调用时才执行；而且 return 不负责打印。'),
step('return 与 print，分别负责什么？','return 把结果交还给程序，print 把内容显示给人看。想让 if 接着判断，应使用函数返回的值。','def is_low_quality(score):\n    return score < 3\n\nresult = is_low_quality(2)\nif result:\n    print("需要复查")','需要复查',['函数返回 True，于是 result 保存 True。','if result 就是判断 result 是否为真。','原例里的 if is_low_quality(score): 是把“调用函数得到结果”和“判断结果”接着写。'],'能把 return 换成 print，其他地方完全不改吗？','不能。只打印而不 return 的函数默认返回 None，后面的 if 就拿不到预期的 True。')]
},
{
intro:'先看 CSV 文件长什么样，再打开它、读一行、转成数字、筛选。这里不会把读文件的一长串写法当作你已经懂了。',
remember:['CSV 是文本表格：第一行字段名，后面每行一条记录。','DictReader 读出的数字通常仍是字符串，计算前要转换。','本站原始 CSV 有重复行；本节只筛选，不会自动去重。'],
steps:[
step('先看原材料：CSV 不是一段 Python','CSV 文件可以用表格软件打开，也可以用文本编辑器打开。逗号分开列，换行分开记录。下面只是文件内容示例。','id,model_version,score\n1,v1,2\n2,v2,5','', ['第一行是字段名，也就是每列叫什么。','第二行表示：id 是 1，版本是 v1，得分是 2。','下载区的完整 CSV 还包含 task_type、prompt，以及重复和缺失记录。'],'这三行里有几条样本记录？','2 条。第一行是表头，不算样本。'),
step('import：先拿到读 CSV 的工具','Python 有一些现成工具，组成一个个模块。csv 是自带的模块，import csv 表示让当前程序可以使用它。','import csv','（这一行没有输出）',['csv 不是要读取的文件名，它是工具模块的名字。','文件名 evaluation.csv 才是实际数据文件。','以后写 csv.DictReader，意思是使用 csv 模块里的 DictReader 功能。'],'import csv 会自动把 evaluation.csv 读进来吗？','不会。import 只引入工具，还没有告诉它要读哪个文件。'),
step('打开文件：with、open、as 分别做什么？','把下载的 evaluation.csv 放到 Python 当前工作目录。open 打开文件；as f 给打开后的文件对象起一个简短名字。','with open("evaluation.csv", encoding="utf-8", newline="") as f:\n    print(f.readline().strip())','id,model_version,task_type,score,prompt',['"evaluation.csv" 是文件路径；找不到它时会报 FileNotFoundError。','encoding="utf-8" 指定文字编码，帮助正确读取中文；newline="" 让 csv 模块处理换行。','with 负责在这段操作结束后关闭文件。f.readline() 读第一行，strip() 去掉行末换行等空白。'],'f 是文件本身的名字吗？','不是。f 是给打开后的文件对象起的变量名，可以改叫 file，只要后面一起改。'),
step('把每一行读成字典','CSV 的表头刚好可以当字典的键。DictReader 负责按表头对应每行的值；list 把读到的记录收集成列表。','import csv\nwith open("evaluation.csv", encoding="utf-8", newline="") as f:\n    reader = csv.DictReader(f)\n    rows = list(reader)\nprint(rows[0]["score"])','2',['reader 是按行读取记录的对象，还不是所有行组成的列表。','rows = list(reader) 把小文件全部读出来，得到列表；这里有 8 条记录。','rows[0] 是第一条字典，rows[0]["score"] 是字符串 "2"。print 不显示引号，所以屏幕上看起来像数字。'],'怎么确认 "2" 是文字而不是数字？','可以看读取规则，或用 print(type(rows[0]["score"]))，结果是 <class \'str\'>。str 表示字符串。'),
step('转换类型：先得到数字，再比较','float 可以把合法的数字文字转成小数。得分可能是 4.5，所以这里用 float，而不是只处理整数的 int。','score_text = "2"\nscore_number = float(score_text)\nprint(score_number)\nprint(score_number < 3)','2.0\nTrue',['第一步拿到文字 "2"。','第二步 float("2") 得到小数 2.0。','第三步比较 2.0 < 3，得到 True。如果文字是 "未知"，float 会报错。'],'空字符串 "" 能直接 float 转成数字吗？','不能，会报 ValueError。需要先处理没有填写得分的记录。'),
step('缺失得分先跳过，再筛选','为了看清顺序，先用两层 if。row 是循环里当前这一条记录，row["score"] 是当前这条记录的得分文本。以下片段接在读取 rows 之后。','for row in rows:\n    score_text = row["score"]\n    if score_text != "":\n        score_number = float(score_text)\n        if score_number < 3:\n            print(row["id"], score_number)','1 2.0\n4 1.0\n6 2.0\n6 2.0',['第一层 if 检查不是空文字，跳过 id=7 的缺失得分。','第二层 if 检查转换后的数字是否小于 3。','id=6 在原始 CSV 里出现两次，所以这里也输出两次。去重是后面 pandas 课程的工作。'],'看到两次 id=6，一定是循环写错了吗？','不一定。这次是原始文件里有两行相同记录，程序如实处理了每一行。'),
step('再看简写里的 and','原来的代码把两个判断写在一行。and 表示“同时满足”，而且左边不成立时，Python 不会继续计算右边。','score_text = ""\nif score_text and float(score_text) < 3:\n    print("低分")','（没有输出，也没有执行 float("")）',['在 if 中，空字符串被视为假；非空字符串被视为真。','左边为空时就停止判断，因此不会转换空文字。','这仍假设非空内容是合法数字；遇到 "未知" 还需要额外处理。初学时可以坚持写成清楚的两层 if。'],'为什么这里的 and 能避免转换空字符串？','因为从左边开始判断，左边为假时就不求右边的值。这叫短路求值。')]
},
{
intro:'先分清“内存里的字典”和“可以保存或发送的文字”，再理解 JSON 转换。每一个函数名都对照输入与输出看。',
remember:['dumps：Python 对象 → JSON 字符串；loads：JSON 字符串 → Python 对象。','带 s 的这两个函数操作字符串；dump 和 load 操作文件。','JSON 的键用双引号；Python 的 None 对应 JSON 的 null。'],
steps:[
step('先回到熟悉的字典','我们先有一条评测记录，model 对应版本，tags 对应一个装着两个文字标签的列表。','result = {"model": "v2", "tags": ["构图", "细节"]}\nprint(result["tags"][0])','构图',['最外层 {} 是字典。','result["tags"] 先得到列表 ["构图", "细节"]。','再用 [0] 得到列表第一个元素 "构图"。这和列表里放字典一样，都可以分步取值。'],'result["model"] 得到什么？','得到字符串 "v2"。'),
step('为什么需要 JSON？','Python 字典是程序里的对象。要存到文件、交给别的程序，常用 JSON 文本作为交换格式。下面两段看起来相似，但类型不同。','import json\nresult = {"model": "v2", "score": 4}\ntext = json.dumps(result)\nprint(text)','{"model": "v2", "score": 4}',['import json 引入 Python 自带的 JSON 工具。','dumps 接收字典，返回一段 JSON 格式的字符串。','text 此时是文字，不是字典，不能直接 text["score"]。'],'dumps 会自动在电脑上新建一个文件吗？','不会。它只是返回字符串；还没有执行写文件。'),
step('loads：从文字还原成能查字段的对象','收到 JSON 文本后，用 loads 解析。解析成功后，才可以像字典一样按键取值。','import json\ntext = \'{"model": "v2", "score": 4}\'\ndata = json.loads(text)\nprint(data["score"])','4',['外面的单引号是 Python 字符串的边界。','里面的双引号属于 JSON 格式，包住键和文字值。','loads 得到字典，data["score"] 才能取出数字 4。'],'data 和 text 在这里是同一种类型吗？','不是。text 是字符串，data 是解析得到的字典。'),
step('保存文件：先打开，再写入','open 的第二个参数 "w" 表示写入模式。用它打开已有文件会覆盖原内容，所以这里用专门的 result.json 文件。','import json\nresult = {"model": "v2", "tags": ["构图", "细节"]}\nwith open("result.json", "w", encoding="utf-8") as f:\n    json.dump(result, f, ensure_ascii=False, indent=2)','文件 result.json 会被写入；这段代码没有打印输出。',['dump 接收对象 result 和目标文件 f，不是把字符串返回给你。','ensure_ascii=False 让中文直接显示，而不是写成转义字符。','indent=2 给嵌套层级加 2 个空格，仅让文件更好读，不改变数据含义。'],'这里为什么用 dump 而不是 dumps？','因为这里要直接写入文件 f；dumps 是得到一个字符串。'),
step('逐个对应，别背四个相似名字','读文件时对应的是 json.load(f)。你只需要先问自己：手上是文件还是字符串？想得到对象还是文字？','import json\nwith open("result.json", encoding="utf-8") as f:\n    restored = json.load(f)\nprint(restored["model"])','v2',['此例需要先执行上一步，生成 result.json。','load 从文件里解析数据；loads 从字符串里解析数据。','JSON 的 null 会变成 Python 的 None，true 会变成 True。'], '接口给你一段 JSON 字符串，应该用哪个函数？','json.loads(text)。不要用 eval 解析外来的文本。',{headers:['操作','输入','得到什么'],rows:[['dumps','Python 对象','JSON 字符串'],['loads','JSON 字符串','Python 对象'],['dump','Python 对象 + 文件','写入文件'],['load','文件','Python 对象']]})]
},
{
intro:'先认识“整张表”和“其中一列”，再做筛选。清洗不是一句命令，而是按明确规则，一步一步减少无效记录。',
remember:['df 是我们给表起的名字；df["score"] 取一列，不是取一行。','条件先生成每行的 True / False，再用 df[条件] 保留 True 对应的行。','清洗每一步都要知道删除了什么、还剩多少条。'],
steps:[
step('pandas 和 DataFrame 到底是什么？','pandas 是处理表格的 Python 工具包；DataFrame 是它用来表示二维表格的对象。先把 DataFrame 理解为“代码里的表格”。','import pandas as pd\ndf = pd.read_csv("evaluation.csv")\nprint(len(df))','8',['import pandas 引入工具；as pd 给 pandas 起个简写。','pd.read_csv 读取 CSV，返回一张 DataFrame。','df 是我们给这张表起的变量名。len(df) 数的是行数，不包括表头。','运行这段代码需要已安装 pandas，并能找到 evaluation.csv；本站只展示参考结果。'],'pd 和 df 是同一件东西吗？','不是。pd 指工具包，df 指用这个工具包读取后得到的那张表。'),
step('整张表里取出一列','df["score"] 的方括号在这里表示按列名取列。这和字典按键取值有些像，但拿到的是整列数据。','scores = df["score"]\nprint(scores.tolist())','[2.0, 5.0, 3.0, 1.0, 4.0, 2.0, 2.0, nan]',['这段接在上一步读取 df 后执行。','scores 包含每一行对应的得分，不是单独某一条样本。','tolist() 只是把这一列转换成容易阅读的列表。nan 表示缺失的数值。'],'df["score"] 会直接把缺失记录删除吗？','不会。取列只是选择数据，还没有执行删除或筛选。'),
step('先统一：能读成数字的变成数字','现实中的得分列可能混着 "4"、"未知" 和空值。to_numeric 尝试把它们统一成数值。','df["score"] = pd.to_numeric(df["score"], errors="coerce")','这一行不打印结果；无法转换的值会变为缺失值。',['先看右边：从 df 取 score 列，交给 to_numeric 转换。','errors="coerce" 表示无法转换时记成缺失，而不是报错停止。','最后看左边：把转换好的整列写回 df 的 score 列。','这里的 = 仍然是“把右边结果交给左边”，没有变成比较。'],'如果某个格子是 "未知"，这一行之后它会变成 0 吗？','不会。它会变成缺失值，避免把“没评分”错当成“得了零分”。'),
step('没有分数的记录，先排除','dropna 的意思是删除含缺失值的记录。subset 指定检查哪些列；这里只要求 score 必须有值。','clean = df.dropna(subset=["score"])\nprint(len(clean))','7',['subset=["score"] 是一个只装了一个列名的列表。','原始 8 行中 id=7 没有得分，被排除，剩 7 行。','dropna 返回处理后的表；用 clean 接住它，原 df 仍可用于检查原始数量。'],'如果 prompt 列为空，但 score 有值，这段会删掉它吗？','不会。这次只根据 score 是否缺失来决定。'),
step('重复记录，再去掉一份','id=6 的记录重复出现了两次。当前练习约定 id 是唯一标识，也就是每个 id 最终只保留一条。','clean = clean.drop_duplicates(subset=["id"])\nprint(len(clean))','6',['drop_duplicates 表示删除重复项。','subset=["id"] 表示只按 id 判断是否重复。','默认保留先出现的那条；如果同 id 的评分不同，需要业务规则决定保留谁，不能盲目去重。'],'两条记录的 id 不同，但分数相同，会被这里删除吗？','不会。这里按 id 去重，不是按 score 去重。'),
step('筛选要拆成两步：做判断，再取行','先判断每一行的得分是否处于 1～5，再把这一串判断结果交给表。True 的行留下，False 的行排除。','valid = clean["score"].between(1, 5)\nclean = clean[valid]\nprint(len(clean))','6',['between(1, 5) 对每行得分做判断，包含 1 和 5 两端。','valid 是与原表行对应的一列 True / False，常被叫作布尔条件。','clean[valid] 根据这一列条件筛选行。这里有效分数都在范围内，所以还是 6 行。'],'如果有一个得分为 9 的记录，valid 对那一行是什么？','False，因此 clean[valid] 会排除它。',{headers:['清洗步骤','行数','本例变化'],rows:[['原始 CSV','8','包含重复和缺失'],['排除缺失评分','7','去掉 id=7'],['按 id 去重','6','id=6 只保留一条'],['分数限定 1～5','6','没有额外越界分数']]})]
},
{
intro:'暂时忘掉长长的 groupby(...).agg(...)。先手工把分数分成两堆、算平均，再让 pandas 做同样的事情。',
remember:['groupby 按字段把记录分组；mean 在各组内算平均。','一条链式表达式，可以拆成多个有名字的中间结果。','均分旁边要放样本量；3 条样本不足以证明全面优劣。'],
steps:[
step('先用纸笔做一次分组','本节使用上一节清洗好的 clean，共 6 条数据。根据 model_version，把属于 v1 的放一堆，v2 的放另一堆。','v1 的得分：2、3、1\nv2 的得分：5、4、2','v1 均分 = (2 + 3 + 1) / 3 = 2.0\nv2 均分 = (5 + 4 + 2) / 3 ≈ 3.67',['上面的内容是手工计算说明，不是 Python 代码。','平均值就是总分除以有分数的记录数。','没有把两个版本的分数混在一起，这就是分组的意义。'],'如果把六个分数混着求平均，能直接比较版本吗？','不能。那样只得到全体的一个平均值，版本之间的差别被混掉了。'),
step('先分组，还没求平均','groupby 可以读作“按……分组”。括号里的列名告诉 pandas 用什么划分组。','groups = clean.groupby("model_version")','这一行创建分组对象，没有打印输出。',['clean 是已经清洗过的表。','"model_version" 是表里真实存在的列名，不是必须照抄的固定词。','groups 暂时描述哪些行属于同一组，还没有得到最终均分表。'],'改成 groupby("task_type") 会按什么分组？','按任务类型分组，例如文生图和图像编辑，而不是按模型版本。'),
step('选分数列，再求每组平均','现在从每个组中只选出 score 列，计算它的平均值。把取列和计算也拆开写。','groups = clean.groupby("model_version")\nscore_groups = groups["score"]\naverages = score_groups.mean()\nprint(averages)','model_version\nv1    2.000000\nv2    3.666667\nName: score, dtype: float64',['groups["score"]：只关心得分，不对 prompt 之类文字列求平均。','mean() 没有额外参数，空括号表示调用求平均功能。','三个动作连起来写，就是 clean.groupby("model_version")["score"].mean()。','dtype: float64 是数值类型说明，现在只需要关注两个均分。'],'这条表达式最后得到的是原始六条记录，还是两个版本的均分？','得到两个版本的均分；分组聚合会把多条明细汇总成较少的结果。'),
step('agg：一次算几种指标','如果还想得到样本数，可以用 agg。先把每一对括号理解成“在哪一列上，用哪种计算”。','summary = clean.groupby("model_version").agg(\n    avg_score=("score", "mean"),\n    sample_num=("score", "count")\n)','avg_score：score 列的均值\nsample_num：score 列的非缺失数量',['avg_score 是你给结果列起的名字。','("score", "mean") 是两个元素组成的元组：先写来源列，再写计算方法。这里先记住这个用法。','第二行同理：数 score 中有值的记录有多少条。本例每组是 3 条。'],'sample_num 是原 CSV 里必须提前有的列吗？','不是，它是你给新统计结果起的列名。原表只需要有 model_version 和 score。'),
step('整理结果：恢复列，再排序','分组后，模型版本默认放在索引位置，可以理解为结果行的标签。reset_index 把它变回普通列，便于保存和继续处理。','summary = summary.reset_index()\nsummary = summary.sort_values("avg_score", ascending=False)\nprint(summary.to_string(index=False))','model_version  avg_score  sample_num\n           v2   3.666667           3\n           v1   2.000000           3',['第一行是整理列的位置，不是重新计算均分。','sort_values 根据 avg_score 排序。ascending=False 表示不要升序，而是从高到低。','to_string(index=False) 是为了整齐显示表，不额外打印行索引；不同版本空格可能略有差别。'],'排序后 v2 在上面，会改变原来计算的均分吗？','不会。只改变行的显示顺序，不改变数值。'),
step('保存，并解释这张表能说明什么','to_csv 把汇总表写到一个新 CSV。index=False 不写额外的行编号，避免文件里多出一列。','summary.to_csv("summary.csv", index=False)','生成 summary.csv；这行本身没有打印输出。',['summary 是结果表，evaluation.csv 是原始数据，二者不要混淆。','本例能说：这批模拟样本里 v2 的平均分更高。','不能直接说：v2 总体一定更强。还需同提示词、同评分条件和更多样本。'],'为什么要把 sample_num 一起交出去？','让看报告的人知道均分基于多少条记录；3 条与 3000 条不能当作同样充分的证据。')]
},
{
intro:'SQL 可以理解为“向表格提问”。先只选列，再筛行，再排序；每加一句都看结果怎么变。',
remember:['SELECT 选列，FROM 指定表，WHERE 筛行。','ORDER BY 排序；ASC 升序，DESC 降序。','下面 SQL 使用清洗后的六条数据，表名是 evaluation_data。'],
steps:[
step('先知道你在查哪张表','数据库可以先理解为管理多张表的地方。SQL 在数据库中执行，不是直接把一段 SQL 粘到 Python 里就会运行。这里使用已导入的 evaluation_data 表。','','',['一行是一条记录，一列是一种字段。','id 是样本编号，model_version 是模型版本，score 是得分。','本站 SQL 例子用清洗后的 6 行；下载 CSV 是未清洗的 8 行，两者不要混用。'],'id 和 score 是两个表名吗？','不是，它们是 evaluation_data 这张表里的两列。',{headers:['id','model_version','score'],rows:[[1,'v1',2],[2,'v2',5],[3,'v1',3],[4,'v1',1],[5,'v2',4],[6,'v2',2]]}),
step('SELECT + FROM：只选你想看的列','把 SQL 翻成中文：从 evaluation_data 这张表里，拿出 id 和 score 两列。','SELECT id, score\nFROM evaluation_data;','返回 6 条记录，每条只展示 id 和 score。未指定排序时，行顺序不保证。',['SELECT 后面列出要显示的字段，多个字段用逗号分开。','FROM 后面是表名。','末尾分号 ; 表示这一条语句结束；换行是为了方便阅读。'],'SELECT * 中的星号是什么意思？','在这里表示所有列，不是乘法。符号含义要结合出现的位置看。'),
step('WHERE：逐行问“你符合条件吗？”','现在只看低于 3 分的记录。WHERE 是筛行，SELECT 是选列，这两个动作分别处理表的两个方向。','SELECT id, model_version, score\nFROM evaluation_data\nWHERE score < 3;','符合条件的 id 为 1、4、6；未指定排序时顺序不保证。',['对 id=1，score=2，小于 3，保留。','对 id=2，score=5，不小于 3，排除。','其他行也逐一检查；3 分不符合“低于 3”。'],'把 < 3 改成 >= 3，会留下哪些 id？','留下 id=2、3、5，分数分别是 5、3、4。'),
step('ORDER BY：让最差的排在前面','筛出低分之后，按 score 升序排列，最低的最先出现。同分时，再按 id 排，方便复查。','SELECT id, model_version, score\nFROM evaluation_data\nWHERE score < 3\nORDER BY score ASC, id ASC;','id=4 → score=1\nid=1 → score=2\nid=6 → score=2',['ASC 是升序，小到大；DESC 是降序，大到小。','先比 score，只有得分一样时才比较后面的 id。','排序不会修改数据库里的分数，只影响这次查询结果的顺序。'],'想把高分放前面，应该用什么？','ORDER BY score DESC。'),
step('LIMIT：最多给我几条？','如果只想快速看最差的两条，就在最后加 LIMIT 2。它限制的是返回数量，不是得分条件。','SELECT id, model_version, score\nFROM evaluation_data\nWHERE score < 3\nORDER BY score ASC, id ASC\nLIMIT 2;','id=4 → score=1\nid=1 → score=2',['先筛低分，再排序，最后只取前两条。','LIMIT 10 最多取十条；如果总共只有三条符合条件，就只给三条。','不排序就 LIMIT，不能保证每次取到你想要的“最差几条”。'],'LIMIT 2 是只取 score=2 的记录吗？','不是，它表示最多返回两行。要限制分数，用 WHERE score = 2。'),
step('文字条件和缺失条件怎么写？','SQL 判断相等用一个 =，与 Python 的 == 不同。文字通常用单引号；缺失值写作 NULL。','SELECT id, score\nFROM evaluation_data\nWHERE model_version = \'v2\'\nORDER BY id;','id=2 → 5\nid=5 → 4\nid=6 → 2',['model_version 是列名，不加引号；\'v2\' 是要匹配的文字值。','找缺失分数用 WHERE score IS NULL。','NULL 不是 0，也不是空字符串，不能用 score = NULL 来正确筛选。'],'想找非缺失分数，用什么条件？','WHERE score IS NOT NULL。本教程的这张 SQL 表已经清洗过，六条都非缺失。')]
},
{
intro:'上节返回一条条样本，这节要得到“每个模型一行”的统计表。先不分组求一次平均，再引入分组。',
remember:['COUNT(*) 数行；COUNT(score) 只数有 score 的行；AVG(score) 求非缺失均值。','GROUP BY 按某个字段分堆，再分别统计。','WHERE 筛原始行，HAVING 筛统计后的组。'],
steps:[
step('先把全表汇总成一个数','你已经会选出 score 列。给它套上 AVG，数据库就会对这些分数求平均。','SELECT AVG(score) AS avg_score\nFROM evaluation_data;','avg_score\n2.833333…',['AVG 是求平均的函数，括号里写要计算的列。','六个分数相加是 17，17 / 6 约为 2.83。','AS avg_score 给这个结果列起名，让报告里不只出现一个复杂表达式。'],'这条结果有六行吗？','没有，只有一个总体平均值，结果是一行。'),
step('COUNT：数的是行，还是有值的格子？','COUNT(*) 数所有记录；COUNT(score) 只数 score 不是 NULL 的记录。在已经清洗的数据里，两者相同。','SELECT COUNT(*) AS rows_n,\n       COUNT(score) AS scored_n\nFROM evaluation_data;','rows_n = 6\nscored_n = 6',['星号在 COUNT(*) 里表示数行，不依赖某个字段是否缺失。','如果另有一行 score=NULL，COUNT(*) 会多 1，COUNT(score) 不会。','AVG 也忽略 NULL，所以要交代均分基于哪些记录。'],'一张表有 10 行，其中 2 行 score 为 NULL，COUNT(score) 是多少？','8；COUNT(*) 则是 10。'),
step('GROUP BY：分成两堆，再各算一次','要比较版本，不能只算总体均分。把 GROUP BY model_version 加进来，数据库会对每个版本各算一次。','SELECT model_version, AVG(score) AS avg_score\nFROM evaluation_data\nGROUP BY model_version\nORDER BY model_version;','v1 → 2.0\nv2 → 3.666667…',['model_version 出现在 SELECT 里，是为了知道每个均分属于谁。','GROUP BY model_version 定义分组依据。','每组把多条记录压缩为一条汇总，不再保留每个样本的 id。'],'为什么不随便在 SELECT 里加一个 id？','每组有多个 id，却只有一行结果；应明确聚合或分组规则，不能随意取一个 id 代表整组。'),
step('WHERE 和 HAVING 放在两个阶段','先用一个具体条件理解：只统计分数至少 3 分的记录，然后只留下有至少 2 条记录的版本组。','SELECT model_version, COUNT(*) AS n\nFROM evaluation_data\nWHERE score >= 3\nGROUP BY model_version\nHAVING COUNT(*) >= 2;','model_version = v2, n = 2',['WHERE 先留下 id=2、3、5。','分组后，v1 只有 1 条，v2 有 2 条。','HAVING 再按“每组记录数至少 2”筛选，最后只留下 v2。'],'WHERE 会在组的平均值算完后才工作吗？','不会。从理解统计口径的角度，它先筛掉原始行，再对剩下的行进行分组统计。',{headers:['阶段','剩下什么'],rows:[['WHERE','id=2、3、5'],['GROUP BY','v1: 1 条；v2: 2 条'],['HAVING','v2: 2 条']]}),
step('再把样本量、均分、排序合起来','现在看原来的综合查询。此处没有 WHERE，因此使用全部六条有效记录。','SELECT model_version,\n       COUNT(*) AS sample_num,\n       AVG(score) AS avg_score\nFROM evaluation_data\nGROUP BY model_version\nHAVING COUNT(*) >= 3\nORDER BY avg_score DESC;','v2：3 条，均分约 3.67\nv1：3 条，均分 2.00',['按版本分组，两个组都各有 3 条。','HAVING >= 3 保留两个组。','ORDER BY avg_score DESC 把较高均分放前面。'],'如果把 HAVING 改成 COUNT(*) > 3，还会有结果吗？','没有。两个组都只有 3 条，没有任何组超过 3 条。')]
},
{
intro:'关联可以理解为“拿同一个编号，把两张表的信息对上”。先摆出两张小表，再一条条配对；最后再写 CASE。',
remember:['ON 说明用哪些字段匹配，字段名不同也可以匹配。','LEFT JOIN 保留左表所有记录；右侧找不到时填 NULL。','先判断 NULL，再判断低分；一对多匹配会产生多行。'],
steps:[
step('为什么会有两张表？','图片样本和人工评分可能分开保存。这里使用一套独立小例子，不是前面六条评测数据：samples 有编号 1、2、3，labels 只有 1 和 3 的评分。','','',['samples 表的 id 标识样本。','labels 表的 sample_id 说明这条评分属于哪个样本。','两个字段名称不一样，但值可以用来对应。'],'样本 2 没出现在 labels 里，说明它得了 0 分吗？','不是，只能说明这张标注表里没有找到它的记录。',{headers:['表','编号字段','得分'],rows:[['samples','id=1','不存得分'],['samples','id=2','不存得分'],['samples','id=3','不存得分'],['labels','sample_id=1','2'],['labels','sample_id=3','4']]}),
step('ON：告诉程序怎样对号入座','ON s.id = l.sample_id 是配对规则：左边样本的 id，等于右边标注的 sample_id，就放在同一条结果里。','FROM samples AS s\nLEFT JOIN labels AS l\nON s.id = l.sample_id','这是查询中的 FROM / JOIN 片段，还不是完整 SELECT 语句。',['AS s 给 samples 起简写 s；AS l 给 labels 起简写 l。','s.id 的点号表示“s 这张表里的 id 列”。','ON 后面的 = 比较两边编号是否相同，不是在改编号。'],'可以把 s 和 l 换成别的名字吗？','可以。它们是临时别名，只要本条查询里所有引用保持一致。'),
step('LEFT JOIN：没有评分，也保留样本','从左表 samples 出发，每个样本都去 labels 里找。样本 2 找不到，也不会被丢掉，只是 score 留为 NULL。','SELECT s.id, l.score\nFROM samples AS s\nLEFT JOIN labels AS l ON s.id = l.sample_id\nORDER BY s.id;','id=1，score=2\nid=2，score=NULL\nid=3，score=4',['LEFT 指保留左边的表，也就是 FROM 后的 samples。','找到匹配就附上对应 score；找不到就用 NULL 表示缺少右侧值。','若用 INNER JOIN，只留下两边匹配成功的记录，样本 2 就不会出现。'],'要追踪“还有哪些样本未标注”，LEFT JOIN 合适吗？','合适，因为它把没有匹配到标注的样本也保留下来了。'),
step('CASE：给每一行贴一个状态标签','先把 CASE 单独看成“按顺序判断的规则表”。WHEN 是“当”，THEN 是“就给这个值”，ELSE 是“其他情况”，END 是结束。','CASE\n  WHEN l.score IS NULL THEN \'未标注\'\n  WHEN l.score < 3 THEN \'低分\'\n  ELSE \'通过\'\nEND AS status','样本 1：低分\n样本 2：未标注\n样本 3：通过',['这是 SELECT 中的一个表达式，不是独立查询。','先检查缺失；有得分时再看是否低于 3。','命中一个条件后就返回标签，AS status 是给新列命名。'],'为什么不只写“低于 3 就低分，否则通过”？','那样 NULL 没有满足低分条件，就可能被归入“通过”，把未评分误当作合格。'),
step('关联可能让记录变多','如果样本 1 有两次人工评分，左表的样本 1 会匹配右表两条记录，产生两行结果。LEFT JOIN 保留左表，不代表结果行数永远不变。','','',['例子：labels 有 (1,2) 和 (1,4) 两条标注。','关联后样本 1 出现两行，分别附上 2 分和 4 分。','要按“图片数”统计时，应先决定如何合并多人评分，不能直接把关联后的行数当图片数。'],'一张图片匹配三条标注，直接 COUNT(*) 得到的是几条？','3 条关联结果，不是 3 张不同图片。',{headers:['左表样本','匹配到的标注','关联结果'],rows:[['id=1','sample_id=1, score=2','1 / 2'],['同一条 id=1','sample_id=1, score=4','1 / 4']]})]
},
{
intro:'目标是“每个模型选两条最低分样本”。先手工给每组编号，再把编号过程写成窗口函数，最后筛选编号。',
remember:['PARTITION BY 定义在谁的范围内分别编号。','ORDER BY 决定组内编号顺序；ROW_NUMBER 从 1 开始编号。','WITH 保存这次查询的中间结果，外层再筛 rn <= 2。'],
steps:[
step('先手工排一次，不急着写 SQL','恢复使用清洗后的 evaluation_data 六条记录。先按模型分两组，各组内部从低分到高分排。','','',['v1：id=4 得 1 分，id=1 得 2 分，id=3 得 3 分。','v2：id=6 得 2 分，id=5 得 4 分，id=2 得 5 分。','每组分别编号 1、2、3，保留编号 1 和 2 即可。'],'如果直接对全表 LIMIT 2，能保证每个模型都有两条吗？','不能。LIMIT 2 只限制全表返回两行，不会自动为每个版本分别挑两条。',{headers:['模型','id','score','组内编号'],rows:[['v1',4,1,1],['v1',1,2,2],['v1',3,3,3],['v2',6,2,1],['v2',5,4,2],['v2',2,5,3]]}),
step('ROW_NUMBER：给每行一个序号','窗口函数可以保留每条明细，同时为它附上一个计算结果。这里附上的结果就是组内序号。','ROW_NUMBER() OVER (...) AS rn','这是表达式骨架；省略号只是占位说明，不是可运行的 SQL。',['ROW_NUMBER() 是编号功能。','OVER(...) 里面说明编号范围和顺序。','rn 是我们给编号列起的名字，可以理解为 row number 的缩写。'],'它会像 GROUP BY 那样把每组压成一行吗？','不会。六条明细仍然保留，只是每条多了一个序号。'),
step('PARTITION BY：在每个模型内部重新开始','OVER 里的 PARTITION BY 可以读成“按这个字段分区”。每个分区独立从 1 开始编号。','ROW_NUMBER() OVER (\n  PARTITION BY model_version\n  ORDER BY score ASC, id ASC\n) AS rn','v1 的 rn：1、2、3\nv2 的 rn：1、2、3',['PARTITION BY model_version 划定范围：同一版本内部计算。','ORDER BY score ASC 把低分放前面。','同分时再看 id；这让编号的选择有明确规则。'],'为什么 v2 的第一个序号不是 4？','因为分区后各组独立编号，不是全表连续编号。'),
step('先得到带序号的完整表','把表达式放回 SELECT。外层 ORDER BY 控制显示顺序；窗口内部 ORDER BY 控制编号顺序，两个位置各有作用。','SELECT id, model_version, score,\n  ROW_NUMBER() OVER (\n    PARTITION BY model_version\n    ORDER BY score ASC, id ASC\n  ) AS rn\nFROM evaluation_data\nORDER BY model_version, rn;','六行都保留，rn 对应第一步表格中的组内编号。',['目前还没有筛掉第 3 名。','窗口内的排序并不等于承诺最终显示顺序，因此在查询末尾也明确排序。','现在中间结果里有 id、model_version、score、rn 四列。'],'现在得到几行？','6 行。编号完成了，但筛选还没做。'),
step('WITH：给中间结果起一个名字','WITH ranked AS (...) 可以先读成“把括号里查出的表，临时叫 ranked”。它不是新建一张永久数据库表。','WITH ranked AS (\n  SELECT id, model_version, score,\n    ROW_NUMBER() OVER (\n      PARTITION BY model_version\n      ORDER BY score ASC, id ASC\n    ) AS rn\n  FROM evaluation_data\n)\nSELECT * FROM ranked\nWHERE rn <= 2\nORDER BY model_version, rn;','v1：id=4、1\nv2：id=6、5',['先执行里面的查询思路，得到带 rn 的中间结果。','外面把 ranked 当成可查询的结果集，再用 WHERE 筛 rn。','不要在计算 rn 的同一层 WHERE 里直接按 rn 过滤；先算好、再筛，最容易读懂。'],'最终返回几行？','4 行：两个模型，各保留两条。'),
step('遇到同分时，想要“固定条数”还是“并列名次”？','ROW_NUMBER 即使遇到同分，也会给不同编号。另一种函数 RANK 可以保留并列名次，它是扩展知识，先理解需求即可。','得分：1、1、2\nROW_NUMBER：1、2、3\n只按 score 排序的 RANK：1、1、3','这是编号规则对比，不是独立 SQL。',['ROW_NUMBER 适合每组最多取固定数量。','RANK 会并列，并可能跳号。','如果 RANK 的排序里还加了唯一 id，同分记录也被区分开，就不再按分数并列。'],'本节想每个模型固定取两条，先学哪一个就够？','ROW_NUMBER。先把固定条数的任务做好，再扩展并列排名。')]
},
{
intro:'不用一次从零写完整项目。我们先手工算清结果，再逐步完成读取、清洗、标记低分和汇总。每一步都检查输入、动作、输出。',
remember:['原始 8 行 → 排除缺失 7 行 → 按 id 去重 6 行。','低分率 = 低于 3 分的有效记录数 / 全部有效记录数。','本项目是教学模拟，不代表任何真实模型的性能。'],
steps:[
step('先把任务翻译成四个小问题','你收到 evaluation.csv，要回答：有多少有效样本？每个版本均分多少？低分比例多少？结果有什么限制？先确定规则，再写代码。','','',['规则 1：score 必须能转成数字，并处于 1～5。','规则 2：本例每个 id 只保留一条，重复保留第一条有效评分记录。','规则 3：低分定义为 score < 3，3 分本身不算低分。'],'在写代码前，为什么要先定义“低分”？','因为 < 3 和 <= 3 会统计出不同数量。代码必须服从已确定的业务口径。'),
step('读取和清洗：每行只做一件事','这次先过滤有效分数，再按 id 去重。这样假如前一条是无效分数、后一条有效，就可以保留有效的一条。本例仍得到同样的 6 行。','import pandas as pd\ndf = pd.read_csv("evaluation.csv")\ndf["score"] = pd.to_numeric(df["score"], errors="coerce")\nscored = df.dropna(subset=["score"])\nvalid = scored[scored["score"].between(1, 5)]\nclean = valid.drop_duplicates(subset=["id"]).copy()\nprint(len(df), len(scored), len(valid), len(clean))','8 7 7 6',['df 是原表，scored 有得分，valid 得分范围有效，clean 又去掉了重复。','copy() 明确复制一份处理后的表，方便后面新增列。','本例没有超范围分数，所以 scored 和 valid 都是 7 行。'],'多次打印行数有什么用？','你能定位每一步排除了多少记录，发现规则是否意外删多了。'),
step('给每行添一个“是否低分”标记','先只对 score 做条件判断，会得到每行的 True / False。把它存进新列 is_low，后面就能统计。','clean["is_low"] = clean["score"] < 3','分数 2 → True\n分数 5 → False\n分数 3 → False\n分数 1 → True\n分数 4 → False\n分数 2 → True',['先看右边：对每个分数判断是否低于 3。','再看左边：给表新增一个叫 is_low 的列，用来保存对应结果。','这列并没有把低分记录删除，只是给每条记录打一个标记。'],'加了 is_low 列后，clean 还是 6 行吗？','是。新增的是列，样本行数没有变。'),
step('为什么 True / False 的平均值能表示比例？','计算均值时，布尔值 True 按 1，False 按 0 参与。v1 的低分标记是 True、False、True，相当于 1、0、1。','v1： (1 + 0 + 1) / 3 = 2/3\nv2： (0 + 0 + 1) / 3 = 1/3','v1 低分率约 66.7%\nv2 低分率约 33.3%',['上面是手工算式，帮助理解，不是要执行的 Python。','分子加起来是低分数量，分母是有效样本数量。','0.3333 是比例，乘以 100% 才是约 33.3%；不要写成 0.3333%。'],'如果三个样本全部低分，均值是多少？','(1+1+1)/3 = 1，也就是 100%。'),
step('一次输出三种指标','现在 agg 的每一行都可以独立翻译：对哪列，做什么计算，新结果叫什么。','report = clean.groupby("model_version").agg(\n    n=("score", "count"),\n    avg=("score", "mean"),\n    low_rate=("is_low", "mean")\n)\nprint(report)','v1：n=3，avg=2.0，low_rate≈0.6667\nv2：n=3，avg≈3.6667，low_rate≈0.3333',['n：对 score 计数，得到有分数的样本量。','avg：对 score 求平均。','low_rate：对 is_low 求平均，得到低分比例。'],'低分率应该对 score 求平均，还是对 is_low 求平均？','对 is_low 求平均。直接对 score 求平均得到的是平均分。',{headers:['版本','有效样本数','平均分','低分数','低分率'],rows:[['v1',3,'2.00',2,'66.7%'],['v2',3,'3.67',1,'33.3%']]}),
step('核对完数字，再写结论','先逐个检查样本数和手算结果是否相同，再解释结果。示例结论可以按下面的结构写进“我的笔记”。','','',['数据口径：8 行模拟记录，排除缺失与重复后得到 6 个有效样本。','发现：本批 v2 均分 3.67，v1 均分 2.00；低分率分别约 33.3% 和 66.7%。','限制：每版仅 3 条，而且提示词没有配对，不能推断总体优劣。','行动：补充相同提示词、相同评分规则的配对样本，并分任务检查低分原因。'],'现在能不能直接宣布 v2 全面优于 v1？','不能。当前只描述这一小批模拟数据，需要更多可比评测来验证。')]
},
{
intro:'最后一节把统计结果变成别人能理解的汇报。先拆清楚“比较什么”，再写分组查询，最后解释限制与后续行动。',
remember:['总体均分之外，还要看不同任务是否表现一致。','结果是观察，原因是待验证的假设，不要混写。','用“口径—发现—限制—行动”组织结论。'],
steps:[
step('总体均分可能掩盖什么？','假设一个版本多测简单题，另一个多测难题，就算总体均分不同，也不一定全是模型能力造成的。所以还要按任务类型分开看。','','',['本例 task_type=text_to_image 表示文生图，edit 表示图像编辑。','两个版本各有两条文生图、一条编辑，但具体提示词仍不一样。','分任务能帮助定位现象，不能自动消除所有比较偏差。'],'只要任务数量一样，就保证比较公平了吗？','不能。题目内容和难度、评分者、评分标准等仍可能不同。'),
step('按两个字段分组，怎么理解？','GROUP BY model_version, task_type 表示：版本相同，并且任务类型也相同的记录，才归为一组。','SELECT model_version, task_type, COUNT(*) AS n\nFROM evaluation_data\nGROUP BY model_version, task_type\nORDER BY model_version, task_type;','v1 / edit：1 条\nv1 / text_to_image：2 条\nv2 / edit：1 条\nv2 / text_to_image：2 条',['先按版本分成 v1、v2。','每个版本再按任务拆开，得到四个组合。','SELECT 同时展示两个字段，才能知道每个结果属于哪一组。'],'这里会产生两个组还是四个组？','四个组，因为数据里实际存在四种“版本 + 任务”组合。'),
step('SQL 里也能用 1 和 0 表示低分','CASE 可以给低于 3 分的记录标 1.0，其余标 0.0。假定数据已排除缺失，再对这些标记求平均。','SELECT id, score,\n  CASE WHEN score < 3 THEN 1.0 ELSE 0.0 END AS is_low\nFROM evaluation_data\nORDER BY id;','id 1、4、6：is_low=1.0\nid 2、3、5：is_low=0.0',['CASE 表达式逐行工作，此时还没有求均值。','小数写法 1.0 / 0.0 有助于让后面的计算按小数处理；不同数据库类型规则不同。','如果包含 NULL，这种 ELSE 会把未评分当非低分，所以必须先明确清洗口径。'],'如果未评分记录也被标 0，低分率可能怎样变化？','分母增大而低分数不变，低分率会被压低。因此不能悄悄把未评分当作非低分。'),
step('把低分标记包进 AVG','就像 Python 先计算括号里的值一样，可以理解为先为每条记录生成 1.0 或 0.0，再在每个组里求它们的平均。','SELECT model_version, task_type,\n       COUNT(*) AS n,\n       AVG(score) AS avg_score,\n       AVG(CASE WHEN score < 3 THEN 1.0 ELSE 0.0 END) AS low_rate\nFROM evaluation_data\nGROUP BY model_version, task_type\nORDER BY model_version, task_type;','具体结果见下表。',['AVG(score) 是平均分。','AVG(CASE ... END) 是低分标记的均值，也就是低分率。','两种 AVG 的输入不同，含义也不同。不要只看函数名。'],'v1 的文生图得分是 2 和 3，低分率是多少？','一条低分 / 两条有效样本 = 0.5，也就是 50%。',{headers:['版本 / 任务','n','均分','低分率'],rows:[['v1 / edit',1,'1.0','100%'],['v1 / text_to_image',2,'2.5','50%'],['v2 / edit',1,'2.0','100%'],['v2 / text_to_image',2,'4.5','0%']]}),
step('看到 100%，先看分母是多少','本例两个模型在编辑任务上的低分率都是 100%，但每个模型只评了一条编辑样本。100% 看起来很强烈，证据却很少。','','',['可以说：本批两条编辑样本得分都低于 3，值得复查。','不能说：两个模型所有编辑任务都会失败。','后续需要看具体失败图片、标注依据，并补充更多同类样本。'],'“编辑任务差”是已证实的总体结论吗？','不是。当前是一个需要进一步验证的信号。'),
step('写成四段，每段只回答一个问题','把下面四点写进“我的笔记”，再用自己的语言改一遍。这才是你可以在面试里讲清楚的项目成果。','','',['口径：使用教学模拟 CSV；排除缺失、无效评分和重复 id，保留 6 条。','发现：v2 本批总体均分较高；编辑子集两版均有低分，但各只有一条。','限制：规模小、提示词未配对，不能据此证明模型总体优劣，也不能确认失败原因。','行动：统一题目和评分标准，扩充配对评测集，再按任务和失败类型复查。'],'面试中应该怎样介绍这个项目的来源？','可以说“用模拟数据独立完成了一次评测数据清洗与分析练习”，不要说成真实线上业务结果。')]
}
];
walkthroughs.forEach((course,i)=>{lessons[i].walkthrough=course;});
